plugins {
    id 'multiloader-loader'
}

loom {
    runs {
        client {
            client()
            programArgs "--username", "DevPlayer"
            runDir("../common/run/client")
        }

        server {
            server()
            runDir("../common/run/server")
        }
    }
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"

    // Dev Environment Only
    localRuntime "com.terraformersmc:modmenu:${project.modmenu_version}"
}