# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Environment Properties
java_version=25
minecraft_version=26.2

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.3
modmenu_version=20.0.1

# NeoForge, see https://neoforged.net for new versions
neoforge_version=26.2.0.53-beta

# Mod Properties
mod_id=intentional_pickup
mod_group=me.voxelbill.intentional_pickup
mod_version=0.1.0+26.2
mod_name=Intentional Pickup
mod_description=A simple mod that makes mobs only pickup items that are intentionally dropped by players.
mod_author=VoxelBill
mod_license=MIT
mod_icon=icon.png
mod_github=https://github.com/VoxelBill/intentional-pickup