modLoader="javafml"
license="${mod_license}"
issueTrackerURL="${mod_github}/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_github}"
    iconFile="${mod_icon}"
    bannerFile="${mod_icon}"
    authors="${mod_author}"
    description='''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.intentional_pickup]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.intentional_pickup]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"